### ISSUE TITLE
ndk-build issue in myNDK

### ISSUE THREAD

**Issue by pradeep8892** [castoryan/ORB-SLAM-Android#17]
when i run this on android studio i got this error in this command "  System.loadLibrary("mono");" which in class myNDK how should i resolve this error

FATAL EXCEPTION: main
                                                   Process: com.example.castoryan.orb, PID: 31860
                                                   java.lang.UnsatisfiedLinkError: Couldn't load mono from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.castoryan.orb-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.castoryan.orb-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                       at java.lang.System.loadLibrary(System.java:526)
                                                       at com.example.castoryan.orb.MyNDK.<clinit>(MyNDK.java:19)
                                                       at com.example.castoryan.orb.MainActivity.onCreate(MainActivity.java:94)

**Comment by sera-wi** [comment]
Does anybody know about this issue?

**Comment by xuxiaowei13** [comment]
I'm having the same issue. @castoryan , could you help to take a look?
Best
