### ISSUE TITLE
Where to get libmono.so for armeabi-v7a device?

### ISSUE THREAD

**Issue by chienpao** [castoryan/ORB-SLAM-Android#3]
as title, please tell me where can get the libmono.so
Because after I implement, showing this log as below,

```
java.lang.UnsatisfiedLinkError: No implementation found for void com.example.castoryan.orb.MyNDK.System(java.lang.String, java.lang.String, int, boolean, long, int) (tried Java_com_example_castoryan_orb_MyNDK_System and Java_com_example_castoryan_orb_MyNDK_System__Ljava_lang_String_2Ljava_lang_String_2IZJI)
                                                       at com.example.castoryan.orb.MyNDK.System(Native Method)
                                                       at com.example.castoryan.orb.MainActivity.onCameraFrame(MainActivity.java:220)
                                                       at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:387)
                                                       at org.opencv.android.JavaCameraView$CameraWorker.run(JavaCameraView.java:346)
```

and I only can find x86's libmono.so in your project.
Thank you!

BR,
Pao

**Comment by castoryan** [comment]
It is defined in the files Application.mk and Android.mk

best wishes,

From CastorYan

**Comment by chienpao** [comment]
@castoryan thanks for your reply

**Comment by eugenelyj** [comment]
@chienpao were you build x86 **.so with the given opencv library in `src/main/jni/lib` ? because when i do that, i got error `Incompatible target`, i am urgent to know that. Thanks for replying.
